DATA ENROLLMENT;	
	set enroll.Enrollement_dw_2020c_2census_dt;
	where location in ('Z-CHEC', 'Z-INSPK', 'FRSC');
RUN; 
PROC SORT DATA=ENROLLMENT;
	BY EMPLID;
RUN;
DATA SIMSTERM;
	SET SIMST.S2020c_2census_dt;
RUN;
PROC SORT DATA=SIMSTERM;
	BY EMPLID;
RUN;
DATA ENROLLED;
	MERGE ENROLLMENT (IN=A) SIMSTERM;
	BY EMPLID;
	IF A=1;
	SORT = SUBSTR(NAME, 1,1);
RUN;
PROC SORT DATA=ENROLLED NODUPKEY;
	BY EMPLID;
RUN;

ods pdf file="C:\Users\jrk0200\UNT System\Special Projects Frisco Data Team - General\alphabetical_students_S20.pdf";
TITLE1 "Distribution of Last Names";
title2 "SPRING 2020";
PROC FREQ DATA=ENROLLED;
	TABLE SORT;
RUN;
ods pdf close;
