*************************************************************************
*																		*
*		Collin Student Counter											*
*																		*
*		TABLE 1 - COUNT OF STUDENTS WITH >= 50% OF COURSES IN COLLIN	*
*					BY DATE AND BY TYPE (COURSES VS SCH)				*
*		TABLE 2 - COUNT OF STUDENTS WITH >= 50% OF COURSES IN COLLIN	*
*					BY NUMBER OF COURSES TAKEN ON MAIN CAMPUS 			*
*																		*
*																		*
*				BY JARED KELLY											*
************************************************************************;		

*LOAD FALL 19 ENROLLMENT AND ADD LOCATION COUNTERS;
DATA WORK.FAL19ENR;
	*SET "C:\Users\jrk0200\UNT System\Clark, Allen - FriscoEnrollment\EnrollmentRecords\ENROLLEMENT_DW_2019Z_%sysfunc(today(),mmddyy6.)";
	SET "C:\Users\jrk0200\UNT System\Clark, Allen - FriscoEnrollment\EnrollmentRecords\ENROLLEMENT_DW_2019Z_090319";
	IF LOCATION IN ('FRSC', 'Z-CHEC', 'Z-INSPK') THEN COUNT_CC = 1;
	ELSE COUNT_DT = 1;
	IF COUNT_CC = 1 THEN SCH_CC = UNT_TAKEN;
	ELSE SCH_DT = UNT_TAKEN;
	IF LOCATION IN ('MAIN') THEN COUNT_MAIN = 1;
RUN;

*LOAD SPRING 19 ENROLLMENT AND ADD LOCATION COUNTERS;
DATA WORK.SPR19ENR;
	SET "C:\Users\jrk0200\UNT System\Clark, Allen - FriscoEnrollment\EnrollmentRecords\enrollement_dw_2019c_census";
	IF LOCATION IN ('FRSC', 'Z-CHEC', 'Z-INSPK') THEN COUNT_CC = 1;
	ELSE COUNT_DT = 1;
	IF COUNT_CC = 1 THEN SCH_CC = UNT_TAKEN;
	ELSE SCH_DT = UNT_TAKEN;
RUN;

*SORT SPRING ENROLLMENT BY EMPLID;
PROC SORT DATA=SPR19ENR;
	BY EMPLID;
RUN;

*COUNT SPRING DENTON CREDIT HOURS BY EMPLID;
data DENTON_SCH;
	set SPR19ENR;
	by EMPLID;
	if First.EMPLID then DENTON_SCH = 0;
	DENTON_SCH + SCH_DT;
	IF LAST.EMPLID THEN OUTPUT;
	KEEP EMPLID DENTON_SCH;
run;
*COUNT SPRING COLLIN CREDIT HOURS BY EMPLID;
data COLLIN_SCH;
	set SPR19ENR;
	by EMPLID;
	if First.EMPLID then COLLIN_SCH = 0;
	COLLIN_SCH + SCH_CC;
	IF LAST.EMPLID THEN OUTPUT;
	KEEP EMPLID COLLIN_SCH;
run;
*COUNT SPRING DENTON COURSE ENROLLMENTS BY EMPLID;
data DENTON_COUNT;
	set SPR19ENR;
	by EMPLID;
	if First.EMPLID then DENTON_COUNT = 0;
	DENTON_COUNT + COUNT_DT;
	IF LAST.EMPLID THEN OUTPUT;
	KEEP EMPLID DENTON_COUNT;
run;
*COUNT SPRING COLLIN COURSE ENROLLMENTS BY EMPLID;
data COLLIN_COUNT;
	set SPR19ENR;
	by EMPLID;
	if First.EMPLID then COLLIN_COUNT = 0;
	COLLIN_COUNT + COUNT_CC;
	IF LAST.EMPLID THEN OUTPUT;
	KEEP EMPLID COLLIN_COUNT;
run;
*MERGE SPRING COUNTS INTO A DATASET FOR "RESULT by DATE" REPORT;
DATA TOTALBY;
	MERGE COLLIN_COUNT COLLIN_SCH DENTON_COUNT DENTON_SCH;
	BY EMPLID;
RUN;

DATA TOTALBY;	*ADD VARIABLES FOR TOTAL COURSES FOR LATER CALCULATION;
	SET TOTALBY;
	TOTAL_COUNT = COLLIN_COUNT + DENTON_COUNT;
	TOTAL_SCH = COLLIN_SCH + DENTON_SCH;
RUN;

DATA TOTALBY;	*CALCULATE RATIO TO FIND 50% THRESHOLD;
	SET TOTALBY;
	COLLIN_COUNT_RATIO = COLLIN_COUNT / TOTAL_COUNT;
	COLLIN_SCH_RATIO = COLLIN_SCH / TOTAL_SCH;
	FORMAT COLLIN_COUNT_RATIO PERCENTN8.1 COLLIN_SCH_RATIO PERCENTN8.1;
RUN;

DATA SCH_RESULTS;	*CREATE RESULTS DATASET WITH ALL STUDENTS >= 50% COLLIN ENROLLMENT BY SCH;
	SET TOTALBY;
	LENGTH RESULT $15. DATE $15.;
	WHERE COLLIN_SCH_RATIO GE .5;
	RESULT = 'By SCH';
	DATE = 'Spring19';
RUN;

DATA COUNT_RESULTS;	*CREATE RESULTS DATASET WITH ALL STUDENTS >= 50% COLLIN ENROLLMENT BY COURSE TOTAL;
	SET TOTALBY;
	LENGTH RESULT $15. DATE $15.;
	WHERE COLLIN_COUNT_RATIO GE .5;
	RESULT = 'By Course Count';
	DATE = 'Spring19';
RUN;

DATA SPRING_RESULTS;		* CREATE FINAL SPRING RESULT DATASET TO MERGE LATER WITH FALL;
	SET SCH_RESULTS COUNT_RESULTS;
	KEEP RESULT DATE;
RUN;

*RE-SORT FALL ENROLLMENT BY EMPLID;
PROC SORT DATA=FAL19ENR;
	BY EMPLID;
RUN;
data DENTON_SCH;	*COUNT FALL DENTON CREDIT HOURS BY EMPLID;
	set FAL19ENR;
	by EMPLID;
	if First.EMPLID then DENTON_SCH = 0;
	DENTON_SCH + SCH_DT;
	IF LAST.EMPLID THEN OUTPUT;
	KEEP EMPLID DENTON_SCH;
run;
data COLLIN_SCH;		*COUNT FALL COLLIN CREDIT HOURS BY EMPLID;
	set FAL19ENR;
	by EMPLID;
	if First.EMPLID then COLLIN_SCH = 0;
	COLLIN_SCH + SCH_CC;
	IF LAST.EMPLID THEN OUTPUT;
	KEEP EMPLID COLLIN_SCH;
run;
data DENTON_COUNT;		*COUNT FALL DENTON COURSES BY EMPLID;
	set FAL19ENR;
	by EMPLID;
	if First.EMPLID then DENTON_COUNT = 0;
	DENTON_COUNT + COUNT_DT;
	IF LAST.EMPLID THEN OUTPUT;
	KEEP EMPLID DENTON_COUNT;
run;
data COLLIN_COUNT;		*COUNT FALL COLLIN COURSES BY EMPLID;
	set FAL19ENR;
	by EMPLID;
	if First.EMPLID then COLLIN_COUNT = 0;
	COLLIN_COUNT + COUNT_CC;
	IF LAST.EMPLID THEN OUTPUT;
	KEEP EMPLID COLLIN_COUNT;
run;
data MAIN_COUNT;		*COUNT FALL MAIN COURSES BY EMPLID;
	set FAL19ENR;
	by EMPLID;
	if First.EMPLID then MAIN_COUNT = 0;
	MAIN_COUNT + COUNT_MAIN;
	IF LAST.EMPLID THEN OUTPUT;
	KEEP EMPLID MAIN_COUNT;
run;

*TABLE2 PROGRAM;
*MERGE COUNTS FOR "DENTON COURSES BY FRISCO STUDENTS" REPORT;
DATA COLLIN_TOTALBY;
	MERGE COLLIN_COUNT DENTON_COUNT MAIN_COUNT;
	BY EMPLID;
	IF COLLIN_COUNT GE DENTON_COUNT THEN COLLIN=1;
RUN;
*SEPARATE RELEVANT OBSERVATIONS TO CREATE COLLIN STUDENT LIST;
DATA COLLIN_TOTALBY;
	SET COLLIN_TOTALBY;
	WHERE COLLIN=1;
	KEEP EMPLID MAIN_COUNT;
RUN;

*GRAB THE DENTON COURSE COUNT OF APPLICABLE STUDENTS (COLLIN);
DATA DENT_COUNT;
	MERGE COLLIN_TOTALBY (IN=A) DENTON_COUNT;
	BY EMPLID;
	IF A=1;
	KEEP EMPLID MAIN_COUNT;
RUN;


* RETURN TO TABLE1 PROGRAM;
*MERGE FALL COUNTS INTO A DATASET FOR TABLE1 REPORT;
DATA TOTALBY;
	MERGE COLLIN_COUNT COLLIN_SCH DENTON_COUNT DENTON_SCH;
RUN;
DATA TOTALBY;		*ADD VARIABLES FOR TOTAL COURSES FOR LATER CALCULATION;
	SET TOTALBY;
	TOTAL_COUNT = COLLIN_COUNT + DENTON_COUNT;
	TOTAL_SCH = COLLIN_SCH + DENTON_SCH;
RUN;
DATA TOTALBY;		*CALCULATE RATIO TO FIND 50% THRESHOLD;
	SET TOTALBY;
	COLLIN_COUNT_RATIO = COLLIN_COUNT / TOTAL_COUNT;
	COLLIN_SCH_RATIO = COLLIN_SCH / TOTAL_SCH;
	FORMAT COLLIN_COUNT_RATIO PERCENTN8.1 COLLIN_SCH_RATIO PERCENTN8.1;
RUN;
DATA SCH_RESULTS;		*CREATE RESULTS DATASET WITH ALL STUDENTS >= 50% COLLIN ENROLLMENT BY SCH;
	SET TOTALBY;
	LENGTH RESULT $15. DATE $15.;
	WHERE COLLIN_SCH_RATIO GE .5;
	RESULT = 'By SCH';
	DATE = 'Fall19';
RUN;
DATA COUNT_RESULTS;		*CREATE RESULTS DATASET WITH ALL STUDENTS >= 50% COLLIN ENROLLMENT BY COURSE TOTAL;
	SET TOTALBY;
	LENGTH RESULT $15. DATE $15.;
	WHERE COLLIN_COUNT_RATIO GE .5;
	RESULT = 'By Course Count';
	DATE = 'Fall19';
RUN;

DATA FINAL_RESULTS;		* CREATE FINAL RESULT DATASET WITH FALL/SPRING MERGE;
	SET SCH_RESULTS COUNT_RESULTS SPRING_RESULTS;
	KEEP RESULT DATE;
RUN;

proc template;
 define style styles.XLsansPrinter;
 parent = styles.sansPrinter;

 /* Change attributes of the column headings */

 style header from header /
 font_size = 11pt
 just = center
 BACKGROUND=GREEN
 vjust = bottom;
 end;
run; quit;

ods tagsets.excelxp file="C:\Users\jrk0200\Desktop\COLLIN_STUDENTS.XML" style=XLSANSPRINTER
    options( embedded_titles='yes' AUTOFIT_HEIGHT='YES'
             sheet_name="COLLIN" suppress_bylines='no'
			 ABSOLUTE_COLUMN_WIDTH='16,7,7,7');

PROC FREQ DATA=FINAL_RESULTS;
	TABLE RESULT*DATE/NOCUM NOPERCENT NOROW NOCOL;
RUN;

ods tagsets.excelxp options(embed_titles_once='yes' autofit_height='yes' sheet_interval='none' 
			sheet_NAME='MAIN' absolute_column_width='10,8,8');

PROC FREQ DATA=DENT_COUNT;
	TABLE MAIN_COUNT/NOCUM NOPERCENT;
RUN;

ods tagsets.excelxp close;
title;


