data test;
	set enrollment;
	IF LOCATION IN ('FRSC', 'Z-INSPK') THEN FRISCO = 1;
	ELSE IF LOCATION IN ('Z-CHEC') THEN CHEC = 1;
	ELSE IF LOCATION IN ('Z-INET-TX', 'Z-INET-OS', 'Z-AOP') THEN ONLINE = 1;
	ELSE IF LOCATION IN ('MAIN') THEN MAIN = 1;
	ELSE SKIP_ = 1;
RUN;
proc sort data=test;
	by emplid;
run;

* CALCULATING THE TOTALS FOR THE VARIABLES;
%MACRO TOTAL(VAR);
	DATA &VAR;		* CALCULATE A SUM OF FRISCO COURSES PER STUDENT;
		SET TEST;
		BY EMPLID;
		if First.EMPLID then TOT_&VAR = 0;
		TOT_&VAR + &VAR;
		IF LAST.EMPLID THEN OUTPUT;
		KEEP EMPLID TOT_&VAR;
	RUN;
%MEND TOTAL;
%TOTAL(FRISCO);
%TOTAL(CHEC);
%TOTAL(ONLINE);
%TOTAL(MAIN);
%TOTAL(SKIP_);

DATA COUNT_TOTAL;
	MERGE FRISCO CHEC ONLINE MAIN SKIP_;
	BY EMPLID;
RUN;

DATA COLLIN_RESULT;
	SET COUNT_TOTAL;
	WHERE TOT_FRISCO > 0 OR TOT_CHEC > 0;
RUN;

DATA REFINED;
	SET COLLIN_RESULT;
	WHERE TOT_MAIN IN (1,2);
RUN;

/*DATA FINAL_RESULT;*/
/*	SET COUNT_TOTAL;*/
/*	LENGTH STATUS $20.;*/
/*	IF SKIP_TOT > 0 THEN STATUS = "SKIP";*/
/*	ELSE IF FRISCO_TOT > 0 AND CHEC_TOT = 0 AND ONLINE_TOT = 0 THEN STATUS = "A)FRISCO";*/
/*	ELSE IF FRISCO_TOT > 0 AND CHEC_TOT = 0 AND ONLINE_TOT > 0 THEN STATUS = "D)FRISCO/ONLINE";*/
/*	ELSE IF FRISCO_TOT > 0 AND CHEC_TOT > 0 AND ONLINE_TOT = 0 THEN STATUS = "C)CHEC/FRISCO";*/
/*	ELSE IF FRISCO_TOT > 0 AND CHEC_TOT > 0 AND ONLINE_TOT > 0 THEN STATUS = "F)CHEC/FRIS/ONLI";*/
/*	ELSE IF FRISCO_TOT = 0 AND CHEC_TOT > 0 AND ONLINE_TOT > 0 THEN STATUS = "E)CHEC/ONLINE";*/
/*	ELSE IF FRISCO_TOT = 0 AND CHEC_TOT > 0 AND ONLINE_TOT = 0 THEN STATUS = "B)CHEC";*/
/*	ELSE STATUS = "RELEVANT";*/
/*RUN;*/
/**/
/*DATA FINAL_RESULT;*/
/*	SET FINAL_RESULT;*/
/*	WHERE STATUS IN ("A)FRISCO", "D)FRISCO/ONLINE", "C)CHEC/FRISCO", "F)CHEC/FRIS/ONLI", "E)CHEC/ONLINE", "B)CHEC");*/
/*RUN;*/

ods tagsets.excelxp file="C:\Users\jrk0200\Desktop\COLLIN_STUDENTS.XML" style=XLSANSPRINTER
    options( embedded_titles='yes' AUTOFIT_HEIGHT='YES'
             sheet_name="COLLIN" suppress_bylines='no');
PROC FREQ DATA=REFINED;
	TABLE TOT_FRISCO*TOT_ONLINE/NOCUM NOPERCENT NOROW NOCOL;
RUN;
ods tagsets.excelxp close;
title;
