PROC IMPORT OUT= WORK.REGISTRAR
            DATAFILE= "C:\Users\jrk0200\UNT System\Registrar - Fall 2019\ntsr_class_listing_all_fall_1198.xls"
            DBMS=EXCELCS REPLACE;
     RANGE="Sheet1$";
     SCANTEXT=YES;
     USEDATE=YES;
     SCANTIME=YES;
RUN;

DATA REG_ENR;		*STEP TO GRAB ONLY THE OBSERVATIONS WE WANT, AND TO CONVERT THEM TO THE ENROLLMENT FORMAT;
	SET REGISTRAR;
	WHERE LOCATION IN ('FRSC', 'Z-CHEC', 'Z-INSPK') OR SUBJECT IN ('BAAS');
   	STRM = TERM;
	ACAD_GROUP = College_School;
	A_GRP_DESCR = College_School_Descr;
	SUBJECT_AORG_DSCR = Department;
	CATALOG_NBR = Catalog;
	CLASS_SECTION = SECTION;
	CRSE_CAREER = CAREER;
	CRSE_DESCR = Course_Descr;
	ENRL_CAP = Cap_Enrl;
	ENRL_TOT = Tot_Enrl;
	CLASS_FACILITY_ID = Facil_ID;
	COURSE = CATX('-', SUBJECT, CATALOG_NBR, CLASS_SECTION);
	DROP TERM College_School College_School_Descr Department Catalog SECTION
	CAREER Course_Descr Cap_Enrl Tot_Enrl Crse_Level Instr_Type Facil_ID Facil_Type
	Mtg_Start Mtg_End Days_of_the_Week MON TUES WED THURS FRI SAT SUN Start_Date
	End_Date EMPLID NAME GRADE_BASE SESSION ACAD_ORG Course_ID CIP_Code
	Wait_Cap Wait_Tot;
RUN;

DATA MISC_ENROLLMENT;
	SET REG_ENR;
	WHERE ENRL_TOT = 0;
RUN;

DATA TEST_ENROLLMENT;
	SET ENROLLMENT;
	WHERE LOCATION IN ('FRSC', 'Z-CHEC', 'Z-INSPK') OR SUBJECT IN ('BAAS');
RUN;

PROC SORT DATA=TEST_ENROLLMENT NODUPKEY;
	BY COURSE;
RUN;
PROC SORT DATA=REG_ENR NODUPKEY;
	BY COURSE;
RUN;

DATA REGIS;
	MERGE TEST_ENROLLMENT (IN=A) REG_ENR;
	BY COURSE;
	IF A=0;
RUN;












PROC CONTENTS DATA=REGISTRAR;
RUN;
PROC CONTENTS DATA=REG_ENR;
RUN;
