LIBNAME UNT1 'S:\UIS\Shared\SAS Data Projects\DATA\Simsterm';
LIBNAME UNT2 'S:\UIS\Shared\SAS Data Projects\DATA';
LIBNAME UNT3 'S:\UIS\Shared\SAS Data Projects\DATA\Enrollment';

DATA DOC_ENROLL;
	SET UNT3.enrollement_dw_2018zag UNT3.enrollement_dw_2019cag UNT3.enrollement_dw_2019gimag;
	KEEP EMPLID COURSE;
RUN;
PROC SORT DATA=DOC_ENROLL;
	BY EMPLID;
RUN;
PROC TRANSPOSE DATA=DOC_ENROLL
				OUT=DOC_ENROLL_TRANSP
				PREFIX=COURSE_;
	VAR COURSE;
	BY EMPLID;
RUN;
DATA DOC_ENROLL_TRANSP;
	SET DOC_ENROLL_TRANSP;
	DROP _NAME_;
RUN;

DATA DOC_SIMS;
	SET UNT1.dw_2018zag_official UNT1.dw_2019cag_official UNT1.dw_2019gimag_official;
	BIRTH_YEAR = YEAR(DATEPART(BIRTHDATE)); 
	DROP NAME EUID SORT_SSN EFC CIP_CODE STDNT_KEY2 FIRST_NAME LAST_NAME 
	SORT_NAME PRIOR_NATIONAL_ID NATIONAL_ID RK105 RK100 RA532 RA538
	EMAIL_ADDRESS CELL_PHONE_NMBR PERM_PHONE_NMBR MAIL_ADDRESS1 MIDDLE_NAME
	MAIN_PHONE_NMBR MAIL_POSTAL MAIL_ADDRESS2 MAIL_ADDRESS3 MAIL_ADDRESS4
	BIRTHDATE;
RUN;
PROC SORT DATA=DOC_SIMS NODUPKEY;
	BY EMPLID;
RUN;
DATA RETAINED;
	SET UNT_81;
	FALL_19 = "Yes";
	KEEP EMPLID FALL_19;
RUN;
PROC SORT DATA=RETAINED NODUPKEY;
	BY EMPLID;
RUN;
DATA GRADS;
	SET UNT2.gradfile_2019m_all_certs;
	WHERE COMPLETION_TERM IN ('1193', '1191', '1188');
	GRAD_FY19 = COMPLETION_TERM_SDESC;
	KEEP EMPLID GRAD_FY19;
RUN;
PROC SORT DATA=GRADS;
	BY EMPLID;
RUN;
PROC SORT DATA=RETAINED NODUPKEY;
	BY EMPLID;
RUN;
DATA DOC_SIMS2; *WITH RETENTION;
	MERGE DOC_SIMS (IN=A) RETAINED GRADS DOC_ENROLL_TRANSP;
	BY EMPLID;
	IF A=1;
RUN;
DATA DOC_SIMS2;
	SET DOC_SIMS2;
	IF FALL_19 = "" THEN TEMP = "No";
	IF TEMP = "No" THEN FALL_19 = "No";
	ID = (emplid + 25005) * 2;
	DROP TEMP EMPLID;
RUN;

PROC EXPORT DATA= WORK.DOC_SIMS2
            OUTFILE= "C:\Users\jrk0200\Desktop\math1680.csv"
            DBMS=CSV LABEL REPLACE;
RUN;
