data FRISCO_IDS;
	set enroll.Enrollement_dw_2020z_%sysfunc(today(), mmddyy6.);
	WHERE LOCATION IN ('FRSC', 'Z-CHEC', 'Z-INSPK') OR SUBJECT IN ('BAAS');
	KEEP EMPLID;
RUN;
PROC SORT DATA=FRISCO_IDS NODUPKEY;
	BY EMPLID;
RUN;
data plans;
	set SIMST.S2020Z_%SYSFUNC(TODAY(), MMDDYY6.);
	keep EMPLID acad_plan plan_descr acad_sub_plan;
run;
DATA FRISCO_PLANS;
	MERGE FRISCO_IDS (IN=A) PLANS;
	BY EMPLID;
	IF A=1;
	ACAD_GRP = CATX(" ~ ", ACAD_PLAN, ACAD_SUB_PLAN);
RUN;

data FRISCO_IDS2;
	set enroll.Enrollement_dw_2020c_2census_dt;
	WHERE LOCATION IN ('FRSC', 'Z-CHEC', 'Z-INSPK') OR SUBJECT IN ('BAAS');
	KEEP EMPLID;
RUN;
PROC SORT DATA=FRISCO_IDS2 NODUPKEY;
	BY EMPLID;
RUN;
data plans2;
	set SIMST.S2020c_2census_dt;
	keep EMPLID acad_plan plan_descr acad_sub_plan;
run;
DATA FRISCO_PLANS2;
	MERGE FRISCO_IDS2 (IN=A) PLANS2;
	BY EMPLID;
	IF A=1;
	ACAD_GRP = CATX(" ~ ", ACAD_PLAN, ACAD_SUB_PLAN);
RUN;

data FRISCO_IDS3;
	set enroll.Enrollement_dw_2019z_census;
	WHERE LOCATION IN ('FRSC', 'Z-CHEC', 'Z-INSPK') OR SUBJECT IN ('BAAS');
	KEEP EMPLID;
RUN;
PROC SORT DATA=FRISCO_IDS3 NODUPKEY;
	BY EMPLID;
RUN;
data plans3;
	set SIMST.S2019z_official;
	keep EMPLID acad_plan plan_descr acad_sub_plan;
run;
DATA FRISCO_PLANS3;
	MERGE FRISCO_IDS3 (IN=A) PLANS3;
	BY EMPLID;
	IF A=1;
	ACAD_GRP = CATX(" ~ ", ACAD_PLAN, ACAD_SUB_PLAN);
RUN;
ODS PDF FILE="C:\Users\jrk0200\UNT System\Special Projects Frisco Data Team - General\FRISCO_plans.PDF";
TITLE "FALL 2020 ACADEMIC PLANS (FRISCO TOUCH)";
PROC FREQ DATA=FRISCO_PLANS ORDER=FREQ;
	TABLE ACAD_GRP / NOCUM NOPERCENT;
RUN;

TITLE "SPRING 2020 ACADEMIC PLANS (FRISCO TOUCH)";
PROC FREQ DATA=FRISCO_PLANS2 ORDER=FREQ;
	TABLE ACAD_GRP / NOCUM NOPERCENT;
RUN;

TITLE "FALL 2019 ACADEMIC PLANS (FRISCO TOUCH)";
PROC FREQ DATA=FRISCO_PLANS3 ORDER=FREQ;
	TABLE ACAD_GRP / NOCUM NOPERCENT;
RUN;
ODS PDF CLOSE;
proc sort data=plans nodupkey;
	by acad_plan acad_sub_plan;
run;
ods csv file="C:\Users\jrk0200\UNT System\Special Projects Frisco Data Team - General\plans.csv";
proc print data=plans;
	var acad_plan plan_descr acad_sub_plan;
run;
ods csv close;


PROC FREQ DATA=FRISCO_PLANS ORDER=FREQ;
	TABLE ACAD_GRP / NOCUM NOPERCENT;
	WHERE acad_GRP contains "BAAS";
RUN;
