DATA SIMSTERM;
  SET 'S:\IRE\SHARED\SAS Simsterm\s2019C_012219';
RUN;
DATA FRESHMAN;
	SET SIMSTERM;
	WHERE CLASS2 = 1;
	RAND = RAND("UNIFORM");
	KEEP EMAIL_ADDRESS RAND;
RUN;
DATA SOPHOMORE;
	SET SIMSTERM;
	WHERE CLASS2 = 2;
	RAND = RAND("UNIFORM");
	KEEP EMAIL_ADDRESS RAND;
RUN;
DATA JUNIOR;
	SET SIMSTERM;
	WHERE CLASS2 = 3;
	RAND = RAND("UNIFORM");
	KEEP EMAIL_ADDRESS RAND;
RUN;
DATA SENIOR;
	SET SIMSTERM;
	WHERE CLASS2 = 4;
	RAND = RAND("UNIFORM");
	KEEP EMAIL_ADDRESS RAND;
RUN;
DATA GRAD;
	SET SIMSTERM;
	WHERE CLASS2 > 4;
	RAND = RAND("UNIFORM");
	KEEP EMAIL_ADDRESS RAND;
RUN;



